// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqIVza2ERsrWd8OQE4EBqTQXPW3bFauXs',
    appId: '1:1038956506487:web:a49460ea44ceba08aac572',
    messagingSenderId: '1038956506487',
    projectId: 'safeher-e17be',
    authDomain: 'safeher-e17be.firebaseapp.com',
    storageBucket: 'safeher-e17be.firebasestorage.app',
    measurementId: 'G-YCG9VTZXZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAzrg02b5-TbC0iIdEpYGLSLysZlvCYHU',
    appId: '1:1038956506487:android:3db1c7b8a4e0a6d1aac572',
    messagingSenderId: '1038956506487',
    projectId: 'safeher-e17be',
    storageBucket: 'safeher-e17be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzhGo2TSAroF_dyW2v-150ugc-md1MjIs',
    appId: '1:1038956506487:ios:742153ed1437c68baac572',
    messagingSenderId: '1038956506487',
    projectId: 'safeher-e17be',
    storageBucket: 'safeher-e17be.firebasestorage.app',
    iosBundleId: 'com.example.safeherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzhGo2TSAroF_dyW2v-150ugc-md1MjIs',
    appId: '1:1038956506487:ios:742153ed1437c68baac572',
    messagingSenderId: '1038956506487',
    projectId: 'safeher-e17be',
    storageBucket: 'safeher-e17be.firebasestorage.app',
    iosBundleId: 'com.example.safeherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqIVza2ERsrWd8OQE4EBqTQXPW3bFauXs',
    appId: '1:1038956506487:web:1b906628c38a69daaac572',
    messagingSenderId: '1038956506487',
    projectId: 'safeher-e17be',
    authDomain: 'safeher-e17be.firebaseapp.com',
    storageBucket: 'safeher-e17be.firebasestorage.app',
    measurementId: 'G-W4DRPRY6EQ',
  );
}
